APT::FTPArchive::Release::Origin "Jelly-Mayhem";
APT::FTPArchive::Release::Label "Jelly-Mayhem";
APT::FTPArchive::Release::Suite "stable";
APT::FTPArchive::Release::Codename "stable";
APT::FTPArchive::Release::Architectures "amd64";
APT::FTPArchive::Release::Components "main";
